# Generated by Django 2.2.10 on 2021-06-24 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='about',
            name='user_location',
        ),
        migrations.RemoveField(
            model_name='about',
            name='user_number',
        ),
    ]
