# Generated by Django 2.2.10 on 2021-06-24 01:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210624_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
