# Generated by Django 2.2.10 on 2021-06-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210624_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
